### ISSUE TITLE
This is shit

### ISSUE THREAD

**Issue by maikka39** [Raymonzut/Personal-Website#4]
https://github.com/Raymonzut/Personal-Website/blob/5c91c10bc076a406dc82bec18f1edee415351972/server/index.js#L10

**Comment by Raymonzut** [comment]
Duplicate of #3

**Comment by maikka39** [comment]
Sorry..

**Comment by maikka39** [comment]
But you opened it because I told you

**Comment by Raymonzut** [comment]
Thx for that!
